version: '3.8'

services:
  computer-use-demo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ${HOME}/.anthropic:/home/computeruse/.anthropic
      - ${HOME}/Downloads/ComputerUse:/home/computeruse/Desktop
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    stdin_open: true  # эквивалент -i
    tty: true        # эквивалент -t
